project:
  type: website
  output-dir: docs

website:
  title: "kakajaam's webiste"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: descriptive_stat.qmd
        text: Descriptive statistics
      - href: cheat_sheet.qmd
        text: cheat sheet

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

